# Generated by Django 3.2.8 on 2021-11-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Photoshoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('tariff', models.CharField(choices=[('mini', 'mini'), ('middle', 'middle'), ('maxi', 'maxi')], max_length=50, verbose_name='Название тарифа')),
                ('date', models.DateTimeField(null=True, verbose_name='Время')),
                ('place', models.CharField(max_length=50, null=True, verbose_name='Место')),
                ('comment', models.TextField(null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Фотосъемка',
                'verbose_name_plural': 'Фотосъемки',
            },
        ),
    ]
